CREATE TABLE `jxarticleupdates` (
	`JXID` CHAR(32) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXARTID` CHAR(32) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXFIELD1` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXTYPE1` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXVALUE1` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXFIELD2` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXTYPE2` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXVALUE2` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXFIELD3` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXTYPE3` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXVALUE3` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_general_ci',
	`JXUPDATETIME` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
	`JXDONE` INT(11) NULL DEFAULT '0',
	`JXTIMESTAMP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
COLLATE='latin1_general_ci'
ENGINE=MyISAM;
