<?php
$sLangName  = "Deutsch";
$iLangNr    = 0;
$aLang = array(
    'jxartup_menu'                   => 'Artikel Updater',
    'JXARTUP_TITLE'                  => 'Artikel Updater',
    
    'JXARTUP_STATUS'                 => 'Status',
    'JXARTUP_ARTNUM'                 => 'Art.-Nr.',
    'JXARTUP_ARTTITLE'               => 'Titel',
    'JXARTUP_DATE'                   => 'Datum',
    'JXARTUP_CHANGES'                => '&Auml;nderungen',
    
    'JXARTUP_EDIT_TITLE'             => 'Update-Job bearbeiten',
    'JXARTUP_CREATE_TITLE'           => 'Neuen Update-Job erstellen',
    'JXARTUP_CREATE'                 => 'Erstellen',
    'JXARTUP_DELETE'                 => 'Eintrag entfernen',
    'JXARTUP_SAVE'                   => 'Speichern',
    'JXARTUP_CANCEL'                 => 'Abbrechen',
    'JXARTUP_PRODUCT'                => 'Artikel',
    'JXARTUP_DATETIME'               => 'Datum/Uhrzeit',
    'JXARTUP_FIELDS'                 => 'Felder und Werte',
    'JXARTUP_last3month'             => 'Letzten 3 Monate',
    'JXARTUP_lastmonth'              => 'Letzten Monat',
    'JXARTUP_lastweek'               => 'Letzte Woche',
    'JXARTUP_yesterday'              => 'Gestern',
    'JXARTUP_today'                  => 'Heute',
    'JXARTUP_tomorrow'               => 'Morgen',
    'JXARTUP_nextweek'               => 'N&auml;chste Woche',
    'JXARTUP_nextmonth'              => 'N&auml;chsten Monat',
    'JXARTUP_next3month'             => 'N&auml;chsten 3 Monate',

    'JXARTUP_TODAYMIDNIGHT_TITLE'    => 'heute, ab Mitternacht',
    'JXARTUP_TOMORROWMIDNIGHT_TITLE' => 'morgen, ab Mitternacht',
    'JXARTUP_2DAYSMIDNIGHT_TITLE'    => '&uuml;bermorgen, ab Mitternacht',
    'JXARTUP_NXTFRIMIDNIGHT_TITLE'   => 'n&auml;chsten Freitag, ab Mitternacht',
    'JXARTUP_NXTSUNMIDNIGHT_TITLE'   => 'n&auml;chsten Sontag, ab Mitternacht',
    'JXARTUP_FIRSTMIDNIGHT_TITLE'    => 'erster Tag n&auml;chsten Monat, ab Mitternacht',
    'JXARTUP_LASTMIDNIGHT_TITLE'     => 'letzter Tag n&auml;chsten Monat, ab Mitternacht',
    'JXARTUP_TODAYMIDNIGHT_ABBR'     => 'hM',
    'JXARTUP_TOMORROWMIDNIGHT_ABBR'  => 'mM',
    'JXARTUP_2DAYSMIDNIGHT_ABBR'     => '&uuml;M',
    'JXARTUP_NXTFRIMIDNIGHT_ABBR'    => 'nFM',
    'JXARTUP_NXTSUNMIDNIGHT_ABBR'    => 'nSM',
    'JXARTUP_FIRSTMIDNIGHT_ABBR'     => 'eTM',
    'JXARTUP_LASTMIDNIGHT_ABBR'      => 'lTM',
    'JXARTUP_OXPRICE'                => 'Preis',
    'JXARTUP_OXTITLE'                => 'Titel',
    'JXARTUP_OXACTIVE'               => 'Aktiv',
    'JXARTUP_OXBPRICE'               => 'Einkaufspreis',
    'JXARTUP_OXTPRICE'               => 'UVP',
    'JXARTUP_OXPRICEA'               => 'Preis A',
    'JXARTUP_OXPRICEB'               => 'Preis B',
    'JXARTUP_OXPRICEC'               => 'Preis C',
    'JXARTUP_OXFREESHIPPING'         => 'Versandkostenfrei',
    'JXARTUP_OPTIONS'                => 'Optionen',
    'JXARTUP_INHERITPRICES'          => 'Preise vererben',
    
    'charset'                        => 'ISO-8859-15',
);

?>