<?php
$sLangName  = "Deutsch";
$iLangNr    = 0;
$aLang = array(
    'jxartup_menu'            => 'Artikel Updater',
    'JXARTUP_TITLE'           => 'Artikel Updater',
    'JXARTUP_EDIT_TITLE'      => 'Update-Job bearbeiten',
    'JXARTUP_CREATE_TITLE'    => 'Neuen Update-Job erstellen',
    'JXARTUP_CREATE'          => 'Erstellen',
    'JXARTUP_DELETE'          => 'Eintrag entfernen',
    'JXARTUP_SAVE'            => 'Speichern',
    'JXARTUP_CANCEL'          => 'Abbrechen',
    'JXARTUP_PRODUCT'         => 'Artikel',
    'JXARTUP_DATETIME'        => 'Datum/Uhrzeit',
    'JXARTUP_FIELDS'          => 'Felder und Werte',
    'JXARTUP_last3month'      => 'Letzten 3 Monate',
    'JXARTUP_lastmonth'       => 'Letzten Monat',
    'JXARTUP_lastweek'        => 'Letzte Woche',
    'JXARTUP_yesterday'       => 'Gestern',
    'JXARTUP_today'           => 'Heute',
    'JXARTUP_tomorrow'        => 'Morgen',
    'JXARTUP_nextweek'        => 'N&auml;chste Woche',
    'JXARTUP_nextmonth'       => 'N&auml;chsten Monat',
    'JXARTUP_next3month'      => 'N&auml;chsten 3 Monate',

    'JXARTUP_TODAYMIDNIGHT_TITLE' => 'heute, ab Mitternacht',
    'JXARTUP_TOMORROWMIDNIGHT_TITLE' => 'morgen, ab Mitternacht',
    'JXARTUP_2DAYSMIDNIGHT_TITLE' => '&uuml;bermorgen, ab Mitternacht',
    'JXARTUP_NXTFRIMIDNIGHT_TITLE' => 'n&auml;chsten Freitag, ab Mitternacht',
    'JXARTUP_NXTSUNMIDNIGHT_TITLE' => 'n&auml;chsten Sontag, ab Mitternacht',
    'JXARTUP_FIRSTMIDNIGHT_TITLE' => 'erster Tag n&auml;chsten Monat, ab Mitternacht',
    'JXARTUP_LASTMIDNIGHT_TITLE' => 'letzter Tag n&auml;chsten Monat, ab Mitternacht',
    'JXARTUP_TODAYMIDNIGHT_ABBR' => 'hM',
    'JXARTUP_TOMORROWMIDNIGHT_ABBR' => 'mM',
    'JXARTUP_2DAYSMIDNIGHT_ABBR' => '&uuml;M',
    'JXARTUP_NXTFRIMIDNIGHT_ABBR' => 'nFM',
    'JXARTUP_NXTSUNMIDNIGHT_ABBR' => 'nSM',
    'JXARTUP_FIRSTMIDNIGHT_ABBR' => 'eTM',
    'JXARTUP_LASTMIDNIGHT_ABBR' => 'lTM',
    'JXARTUP_OXPRICE'         => 'Preis',
    'JXARTUP_OXTITLE'         => 'Titel',
    'JXARTUP_OXACTIVE'        => 'Aktiv',
    'JXARTUP_OXBPRICE'        => 'Einkaufspreis',
    'JXARTUP_OXTPRICE'        => 'UVP',
    'JXARTUP_OXPRICEA'        => 'Preis A',
    'JXARTUP_OXPRICEB'        => 'Preis B',
    'JXARTUP_OXPRICEC'        => 'Preis C',
    'JXARTUP_OXFREESHIPPING'  => 'Versandkostenfrei',
    'JXARTUP_OPTIONS'         => 'Optionen',
    'JXARTUP_INHERITPRICES'   => 'Preise vererben',
    
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES1'   => 'Verzeichnis 1',
    'SHOP_MODULE_sJxFilesDir1Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir1Title'            => 'Titel',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES2'   => 'Verzeichnis 2',
    'SHOP_MODULE_sJxFilesDir2Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir2Title'            => 'Titel',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES3'   => 'Verzeichnis 3',
    'SHOP_MODULE_sJxFilesDir3Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir3Title'            => 'Titel',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES4'   => 'Verzeichnis 4',
    'SHOP_MODULE_sJxFilesDir4Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir4Title'            => 'Titel',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES5'   => 'Verzeichnis 5',
    'SHOP_MODULE_sJxFilesDir5Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir5Title'            => 'Titel',
    
    'charset'                 => 'ISO-8859-15',
);

?>