<?php
$sLangName  = "English";
$iLangNr    = 1;
$aLang = array(
    'jxartup_menu'                   => 'Product Updater',
    'JXARTUP_TITLE'                  => 'Product Updater',
    
    'JXARTUP_STATUS'                 => 'Status',
    'JXARTUP_ARTNUM'                 => 'Prod.-No.',
    'JXARTUP_ARTTITLE'               => 'Title',
    'JXARTUP_DATE'                   => 'Date',
    'JXARTUP_CHANGES'                => 'Changes',
    
    'JXARTUP_EDIT_TITLE'             => 'Edit Update Job',
    'JXARTUP_CREATE_TITLE'           => 'Create new Update Job',
    'JXARTUP_CREATE'                 => 'Create',
    'JXARTUP_RUNNOW'                 => 'Run now',
    'JXARTUP_DELETE'                 => 'Remove entry',
    'JXARTUP_SAVE'                   => 'Save',
    'JXARTUP_CANCEL'                 => 'Cancel',
    'JXARTUP_PRODUCTID'              => 'Prod.-UID or -No.',
    'JXARTUP_PRODUCT'                => 'Product',
    'JXARTUP_DATETIME'               => 'Date/Time',
    'JXARTUP_FIELDS'                 => 'Fields and Values',
    'JXARTUP_last3month'             => 'Last 3 Month',
    'JXARTUP_lastmonth'              => 'Last Month',
    'JXARTUP_lastweek'               => 'Last Week',
    'JXARTUP_yesterday'              => 'Yesterday',
    'JXARTUP_today'                  => 'Today',
    'JXARTUP_tomorrow'               => 'Tomorrow',
    'JXARTUP_nextweek'               => 'Next Week',
    'JXARTUP_nextmonth'              => 'Next Month',
    'JXARTUP_next3month'             => 'Next 3 Month',

    'JXARTUP_TODAY_TITLE'            => 'today, Midnight',
    'JXARTUP_TOMORROW_TITLE'         => 'tomorrow, Midnight',
    'JXARTUP_2DAYS_TITLE'            => 'day after tomorrow, Midnight',
    'JXARTUP_NXTSAT_TITLE'           => 'next Saturday, Midnight',
    'JXARTUP_NXTMON_TITLE'           => 'next Monday, Midnight',
    'JXARTUP_FIRSTDAY_TITLE'         => 'fist day of next month, Midnight',
    'JXARTUP_LASTDAY_TITLE'          => 'last day of next month, Midnight',
    'JXARTUP_TODAY_ABBR'             => 'hM',
    'JXARTUP_TOMORROW_ABBR'          => 'mM',
    'JXARTUP_2DAYS_ABBR'             => '2dM',
    'JXARTUP_NXTSAT_ABBR'            => 'nSM',
    'JXARTUP_NXTMON_ABBR'            => 'nMM',
    'JXARTUP_FIRSTDAY_ABBR'          => 'eTM',
    'JXARTUP_LASTDAY_ABBR'           => 'lTM',
    'JXARTUP_OXPRICE'                => 'Price',
    'JXARTUP_OXTITLE'                => 'Title',
    'JXARTUP_OXACTIVE'               => 'Active',
    'JXARTUP_OXBPRICE'               => 'Purchase Price',
    'JXARTUP_OXTPRICE'               => 'RRP',
    'JXARTUP_OXPRICEA'               => 'Price A',
    'JXARTUP_OXPRICEB'               => 'Price B',
    'JXARTUP_OXPRICEC'               => 'Price C',
    'JXARTUP_OXFREESHIPPING'         => 'Free Shipping',
    'JXARTUP_OXMINDELTIME'           => '',
    'JXARTUP_OXMAXDELTIME'           => '',
    'JXARTUP_OXDELTIMEUNIT'          => '',
    'JXARTUP_OXSTOCK'                => '',
    'JXARTUP_OXSTOCKFLAG'            => '',
    'JXARTUP_OXSTOCKTEXT'            => '',
    'JXARTUP_OXNOSTOCKTEXT'          => '',
    'JXARTUP_OPTIONS'                => 'Options',
    'JXARTUP_INHERITVALUES'          => 'Inherit values to variants',
    'JXARTUP_READONLYINFO'           => 'This entry was already processed and cannot be edited anymore',
    'JXARTUP_INHERITINFO'            => 'Values will be inherited',
    
    'JXARTUP_ERR'                    => 'Error',
    'JXARTUP_ERR_ID_NOT_FOUND'       => 'Given Prod.-UID or Prod.-No. not found.',
    
    'SHOP_MODULE_GROUP_JXARTUP_DISPLAY'          => 'Display',
    'SHOP_MODULE_sJxArtUpDisplayType'            => 'Default Display',
    'SHOP_MODULE_sJxArtUpDisplayType_list'       => 'List',
    'SHOP_MODULE_sJxArtUpDisplayType_calendar'   => 'Calendar',
    
    'charset'                        => 'ISO-8859-15'
);

?>