<?php
$sLangName  = "Deutsch";
$iLangNr    = 0;
$aLang = array(
    'jxartup_menu'                   => 'Artikel Updater',
    'JXARTUP_TITLE'                  => 'Artikel Updater',
    
    'JXARTUP_STATUS'                 => 'Status',
    'JXARTUP_ARTNUM'                 => 'Art.-Nr.',
    'JXARTUP_ARTTITLE'               => 'Titel',
    'JXARTUP_DATE'                   => 'Datum',
    'JXARTUP_CHANGES'                => '&Auml;nderungen',
    
    'JXARTUP_MONDAY'                 => 'Montag',
    'JXARTUP_TUESDAY'                => 'Dienstag',
    'JXARTUP_WEDNESDAY'              => 'Mittwoch',
    'JXARTUP_THURSDAY'               => 'Donnerstag',
    'JXARTUP_FRIDAY'                 => 'Freitag',
    'JXARTUP_SATURDAY'               => 'Samstag',
    'JXARTUP_SUNDAY'                 => 'Sonntag',
    
    'JXARTUP_EDIT_TITLE'             => 'Update-Job bearbeiten',
    'JXARTUP_CREATE_TITLE'           => 'Neuen Update-Job erstellen',
    'JXARTUP_CREATE'                 => 'Erstellen',
    'JXARTUP_RUNNOW'                 => 'Jetzt ausf&uuml;hren',
    'JXARTUP_DELETE'                 => 'Eintrag entfernen',
    'JXARTUP_SAVE'                   => 'Speichern',
    'JXARTUP_CANCEL'                 => 'Abbrechen',
    'JXARTUP_PRODUCTID'              => 'Art.-UID od. -Nr.',
    'JXARTUP_PRODUCT'                => 'Artikel',
    'JXARTUP_DATETIME'               => 'Datum/Uhrzeit',
    'JXARTUP_FIELDS'                 => 'Felder und Werte',
    'JXARTUP_last3month'             => 'Letzten 3 Monate',
    'JXARTUP_lastmonth'              => 'Letzten Monat',
    'JXARTUP_lastweek'               => 'Letzte Woche',
    'JXARTUP_yesterday'              => 'Gestern',
    'JXARTUP_today'                  => 'Heute',
    'JXARTUP_tomorrow'               => 'Morgen',
    'JXARTUP_nextweek'               => 'N&auml;chste Woche',
    'JXARTUP_nextmonth'              => 'N&auml;chsten Monat',
    'JXARTUP_next3month'             => 'N&auml;chsten 3 Monate',

    'JXARTUP_TODAY_TITLE'            => 'heute, ab Mitternacht',
    'JXARTUP_TOMORROW_TITLE'         => 'morgen, ab Mitternacht',
    'JXARTUP_2DAYS_TITLE'            => '&uuml;bermorgen, ab Mitternacht',
    'JXARTUP_NXTSAT_TITLE'           => 'n&auml;chsten Samstag, ab Mitternacht',
    'JXARTUP_NXTMON_TITLE'           => 'n&auml;chsten Montag, ab Mitternacht',
    'JXARTUP_FIRSTDAY_TITLE'         => 'erster Tag n&auml;chsten Monat, ab Mitternacht',
    'JXARTUP_LASTDAY_TITLE'          => 'letzter Tag n&auml;chsten Monat, ab Mitternacht',
    'JXARTUP_TODAY_ABBR'             => 'hM',
    'JXARTUP_TOMORROW_ABBR'          => 'mM',
    'JXARTUP_2DAYS_ABBR'             => '&uuml;M',
    'JXARTUP_NXTSAT_ABBR'            => 'nSM',
    'JXARTUP_NXTMON_ABBR'            => 'nMM',
    'JXARTUP_FIRSTDAY_ABBR'          => 'eTM',
    'JXARTUP_LASTDAY_ABBR'           => 'lTM',
    'JXARTUP_OXPRICE'                => 'Preis',
    'JXARTUP_OXTITLE'                => 'Titel',
    'JXARTUP_OXACTIVE'               => 'Aktiv',
    'JXARTUP_OXBPRICE'               => 'Einkaufspreis',
    'JXARTUP_OXTPRICE'               => 'UVP',
    'JXARTUP_OXPRICEA'               => 'Preis A',
    'JXARTUP_OXPRICEB'               => 'Preis B',
    'JXARTUP_OXPRICEC'               => 'Preis C',
    'JXARTUP_OXFREESHIPPING'         => 'Versandkostenfrei',
    'JXARTUP_OPTIONS'                => 'Optionen',
    'JXARTUP_INHERITVALUES'          => 'Werte auf Varianten vererben',
    'JXARTUP_READONLYINFO'           => 'Dieser Eintrag wurde bereits ausgef&uuml;hrt und kann daher nicht mehr bearbeitet werden',
    'JXARTUP_INHERITINFO'            => 'Werte werden vererbt',
    
    'JXARTUP_ERR'                    => 'Fehler',
    'JXARTUP_ERR_ID_NOT_FOUND'       => 'Angegebene Art.-UID oder Art.-Nr. nicht gefunden.',
    
    'SHOP_MODULE_GROUP_JXARTUP_DISPLAY'         => 'Anzeige',
    'SHOP_MODULE_sJxArtUpDisplayType'           => 'Standard-Anzeige',
    'SHOP_MODULE_sJxArtUpDisplayType_list'      => 'Liste',
    'SHOP_MODULE_sJxArtUpDisplayType_calendar'  => 'Kalender',
    
    'charset'                        => 'ISO-8859-15'
);

?>